package mai.par.trains.predicates;

public enum TrainPredicate {
	PR_EMPTY, PR_FREE, 
	PR_FREELOCOMOTIVE, PR_INFRONTOF, PR_LOADED,
	PR_ONSTATION, PR_TOWED, 
	PR_USEDRAILWAYS_NOTFULL,PR_USEDRAILWAYS_INCREASE, PR_USEDRAILWAYS_DECREASE;
}
